name: GitHub Actions

on:
    push:
      branches: [ main ]


jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Install Python dependencies
          run: pip install -r requirements.txt
        - name: Build frontend
          run: npm install && npm run build
        - uses: actions/checkout@v3
        

    deploy:

      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Deploy to AWS
          run: ./deploy.sh

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch }}