name: Node Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: rebuild
        run: npm i

      - name: pm2 run
        run: cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/ && pm2 start "npm run dev" --name HokieGPT

      - name: secrets
        run: echo "\nTOGETHER_AI_API_KEY=${{ secrets.TOGETHER_AI_API_KEY }}\nNEXT_PUBLIC_BYTESCALE_API_KEY=${{ secrets.NEXT_PUBLIC_BYTESCALE_API_KEY }}\nOPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}\nPINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}\nCLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}\nNEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}\nPOSTGRES_URL=${{ secrets.POSTGRES_URL }}\nPOSTGRES_URL_NON_POOLING=${{ secrets.POSTGRES_URL_NON_POOLING }}\nPOSTGRES_PRISMA_URL=${{ secrets.POSTGRES_PRISMA_URL }}" >> ./.env
          