name: Node Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # - name: rebuild
      #   run: npm i

      - name: pm2 run
        run: cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/ && pm2 start "npm run dev" --name HokieGPT

      
