name: Node Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: pm2 stop
        run: pm2 stop 0

      - name: rebuild
        run: npm i

      - name: pm2 run
        run: pm2 start 0

      
