name: Node Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: rebuild
        run: npm i

      - name: pm2 run
        run: pm2 start _work/HokieGPT/HokieGPT/process.json

      
