name: Automate Pull

on:
  push:
    branches: [ main ]

jobs:
  run_pull:
    runs-on: self-hosted

    steps:
      - name: sudo su
        run: echo sudo su
      - uses: actions/checkout@v2

      
