name: Node Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: pm2 stop
        run: pm2 stop 0

      - name: rebuild
        run: npm i

      - name: secrets
        run: |
          printf "\nTOGETHER_AI_API_KEY=${{ secrets.TOGETHER_AI_API_KEY }}\n
          NEXT_PUBLIC_BYTESCALE_API_KEY=${{ secrets.NEXT_PUBLIC_BYTESCALE_API_KEY }}\n
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}\n
          MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}\n
          PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}\n
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}\n
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}\n
          POSTGRES_URL=${{ secrets.POSTGRES_URL }}\n
          POSTGRES_URL_NON_POOLING=${{ secrets.POSTGRES_URL_NON_POOLING }}\n
          POSTGRES_PRISMA_URL=${{ secrets.POSTGRES_PRISMA_URL }}" >> ./.env

      - name: pm2 run
        run: cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/ && pm2 delete all && pm2 start "npm run dev" --name HokieGPT_node
        
        
      - name: python installs
        run: cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/python_api && pip install requirements.txt && apt-get install poppler poppler-utils

      - name: pm2 run python
        run: |
          cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/python_api && pm2 start input_classifier.py
          cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/python_api && pm2 start ls_identifier.py
          cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/python_api && pm2 start ls_adjuster.py
          cd /home/ec2-user/actions-runner/_work/HokieGPT/HokieGPT/python_api && pm2 start quiz_gen.py
